<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HRMS.Domain\HRMS.Domain.csproj" />
    <ProjectReference Include="..\HRMS.Infrastructure\HRMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
